# Generated by Django 3.1.4 on 2021-01-01 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_seasonal_specials'),
    ]

    operations = [
        migrations.AddField(
            model_name='seasonal',
            name='gender',
            field=models.CharField(choices=[('M', 'Men'), ('W', 'Women'), ('U', 'Unisex')], default='Unisex', max_length=10),
        ),
        migrations.AddField(
            model_name='specials',
            name='gender',
            field=models.CharField(choices=[('M', 'Men'), ('W', 'Women'), ('U', 'Unisex')], default='Unisex', max_length=10),
        ),
    ]
