# Generated by Django 3.1.4 on 2021-01-02 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_auto_20210101_0115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='gender',
            field=models.CharField(default='Unisex', max_length=10),
        ),
        migrations.AlterField(
            model_name='seasonal',
            name='date',
            field=models.CharField(blank=True, default='January', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='seasonal',
            name='gender',
            field=models.CharField(default='Unisex', max_length=10),
        ),
        migrations.AlterField(
            model_name='specials',
            name='gender',
            field=models.CharField(default='Unisex', max_length=10),
        ),
    ]
