# Generated by Django 3.1.4 on 2021-01-02 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_auto_20210102_1747'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='specials',
            name='category',
        ),
        migrations.DeleteModel(
            name='Seasonal',
        ),
        migrations.DeleteModel(
            name='Specials',
        ),
    ]
